version: '3'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
    volumes:
      - .:/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
